openapi: 3.0.2

info:
  title: Capture model
  version: 1.0.0

paths: {}

components:
  schemas:
    Capture:
      description: >-
        Capture model
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        ports:
          description: >-
            A list of port names to configure capture settings on
          type: array
          items:
            type: string
        filters:
          type: string
        