openapi: 3.1.0

info:
  title: Capture models
  version: 1.0.1

components:
  schemas:
    Capture.Capture:
      description: >-
        Capture model
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        ports:
          description: >-
            A list of port names to configure capture settings on
          type: array
          items:
            type: string
        filters:
          type: string
        