openapi: 3.0.2

info:
  title: Capture schemas
  version: 1.0.0

paths: {}

components:
  schemas:
    Capture:
      type: object
      properties:
        ports:
          description: >-
            A list of ports to configure capture settings on
          type: array
          items:
            type: string
        filters:
          type: string
        