language: python
python:
- '3.8.5'
install:
- pip install pyaml
- pip install jsonpath-ng
- pip install openapi-spec-validator
script:
- python bundler.py
deploy:
  provider: releases
  file: openapi.yaml
  skip_cleanup: true
  api_key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAr0GlJBKQZG3I3ZHhrJDzqQa8YXxclqw7e+ML1WRgTBVkjmyhtMK3rAXWwpn3nfmIOJ1WLtPBptPnOiNhr0c9QUwN8AbZagQQaMXZMgcFH7cZztVZ779K8Ghe96TtUOoruZbmQ9IfUPG42O1rHilyAifK+9xZu4Dne7mih5yzxpvwwO1YX8vIXX2MQjeN8Pb0sKaT6UDORhmqVfN6nh58tB+744C4qvAofh/zmJlTHnHNgOLBBwqcoOBeK2B7sfuZob5w8vMDDk2/ce1cX8lo1CBjObAMrN55VJPBLL65dkaITQ2mse0jA3yRDWwaHOHVjXNlOJ5qoRvVMdwdQj02Bw== rsa-key-20200811


