language: python
python:
- '3.8.5'
install:
- pip install pyaml
- pip install jsonpath-ng
- pip install openapi-spec-validator
script:
- python bundler.py
deploy:
  provider: releases
  file: openapi.yaml
  skip_cleanup: true


