components:
  schemas:
    Device.RsvpRouter.P2pIngressLsp:
      x-status: under-review
      x-include:
      - '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        A container of properties for a P2p Ingress Lsp.
      type: object
      properties:
        remote_address:
          description: >-
            IPv4 address of the RSVP egress for this Lsp.
          type: string
          format: ipv4
          default: 0.0.0.0
        tunnel_id:
          description: |-
            Tunnel Id of the P2P Lsp. 
          type: integer
          default: 1    
        lsp_id:
          description: |-
            Lsp Id of the P2P Lsp. 
          type: integer
          default: 1
          minimum: 0
          maximum: 65535
        