components:
  schemas:
    Rsvp.LspInterface.IngressP2PLSP:
      description: >-
        Configuration for one RSVP Ingress point-to-point LSP.
      type: object
      required: [remote_address]
      properties:
        remote_address:
          description: >-
            IPv4 address of the remote endpoint of the LSP.
          type: string
          format: ipv4
        tunnel_id:
          description: >-
            The Tunnel ID of the RSVP LSP. Carried in the SESSION object in Path Messages.
          type: integer
          default: 1
          minimum: 1
          maximum: 65535
        lsp_id:
          description: >-
            The LSP ID of the RSVP LSP. Carried in the SENDER_TEMPLATE object in Path Messages.
          type: integer
          default: 1
          minimum: 1
          maximum: 65535
        refresh_interval:
          description: >-
             The refresh interval in ms at which refresh Path Messages are sent. 
             The actual refresh interval is jittered by upto 50%.
             There is no specification specified maximum value. For clarity, setting the maximum to 1 hour. 
          type: integer
          default: 30000
          minimum: 1000
          maximum: 3600000
        timeout_multiplier:
          description: >-
             The number of missed Path refreshes after which a recieving node should consider the LSP state to have timed out.
             There is no specification specified maximum value. Setting the maximum allowed value to 10 .
          type: integer 
          default: 3
          minimum: 1
          maximum: 10
        backup_lsp_id:
          description: >-
             The LSP id that will be used when creating a Make-Before-Break LSP when the active LSP is using lsp_id.
             If the active LSP on which Make-Before-Break is being done is using the backup_lsp_id, the new LSP created will toggle to 
             use the lsp_id instead.
          type: integer 
          default: 2
          minimum: 1
          maximum: 65535
        lsp_switchover_delay:
          description: >-
            The amount of delay in seconds that an implementation should wait for before switching traffic to the new LSP created after 
            a Make-Before-Break is done on an LSP. The default value is 0 which means to switch immediately.
            There is no specification specified maximum value. Setting maximum allowed value to 1 minute. 
          type: integer
          default: 0
          minimum: 0
          maximum: 60
        reevaluation_request_interval:
          description: >-
            If value is set to '0' , don't send periodic Path Re-optimization requests.
            If value is set to a non-zero value, send Path Re-optimization requests at interval of specified interval (in seconds).
            If a PathError is recieved in response to the request with Error Code set to Notify and Error Value as one of 
            Preferable path exists, Local link maintenance required, Local node maintenance required or Tunnel Locally Repaired,
            the ingress will initiate Make Before Break procedures to re-optimize the LSP. (RFC4736).          
          type: integer
          default: 0
          minimum: 0
          maximum: 3600     
        session_attribute:
          description: |-
            This contains the values of the fields to be included in the SESSION_ATTRIBUTE object in the Path Message sent for the LSP.            
          $ref: './rsvpSessionAttribute.yaml#/components/schemas/Rsvp.SessionAttribute'
        tspec:
          description: |-
            This contains the values of the fields to be included in the TSPEC object in the Path Message sent for the LSP.            
          $ref: './rsvpTspec.yaml#/components/schemas/Rsvp.Tspec'
        fast_reroute:
          description: |-
            This contains the values of the fields to be included in the FAST_REROUTE object in the Path Message sent for the LSP. 
            This is an optional object . If this attribute is not included , the FAST_REROUTE object will not be included.           
          $ref: './rsvpFastReroute.yaml#/components/schemas/Rsvp.FastReroute'
        ero:
          description: |-
            This contains the values of the fields to be included in the ERO object in the Path Message sent for the LSP. 
            This is an optional object . If this attribute is not included , the ERO object will not be included.           
          $ref: './rsvpEro.yaml#/components/schemas/Rsvp.Ero'