components:
  schemas:
    Rsvp.LspInterface.IngressP2PLSP:
      description: >-
        Configuration for one RSVP Ingress point-to-point LSP.
      type: object
      required: [remote_address]
      properties:
        remote_address:
          description: >-
            IPv4 address of the remote endpoint of the LSP.
          type: string
          format: ipv4
        tunnel_id:
          description: >-
            The Tunnel ID of the RSVP LSP. Carried in the SESSION object in Path Messages.
          type: integer
          format: int
          default: 1
          minimum: 1
          maximum: 65535
        lsp_id:
          description: >-
            The LSP ID of the RSVP LSP. Carried in the SENDER_TEMPLATE object in Path Messages.
          type: integer
          format: int
          default: 1
          minimum: 1
          maximum: 65535
        bandwidth:
          description: >- 
            @TODO: Why hidden.
            The bandwidth requested for the LSP in bytes per second.
          type: integer
          format: int64
          default: 1
          minimum: 1
          maximum: 4294967295
        refresh_interval:
          description: >-
             The refresh interval in ms at which refresh Path Messages are sent. 
             The actual refresh interval is jittered by upto 50%.
             There is no specification specified maximum value. For clarity, setting the maximum to 1 hour. 
          type: integer
          format: int
          default: 30000
          minimum: 1000
          maximum: 3600000
        timeout_multiplier:
          description: >-
             The number of missed Path refreshes after which a recieving node should consider the LSP state to have timed out.
             There is no specification specified maximum value. Setting the maximum allowed value to 10 .
          type: integer 
          format: int
          default: 3
          minimum: 1
          maximum: 10
        lsp_switchover_delay:
          description: >-
            The amount of delay in ms that an implementation should wait for before switching traffic to the new LSP created after 
            a Make-Before-Break is done on an LSP. The default value is 0 which means to switch immediately.
            An implementation should support at least a minimum delay value of 50ms .
            If a delay value is supplied which is lesser than the minimum delay value supported , a warning should be provided to 
            indicate that the minimum value of LSP switchover delay is automatically increased to the supported minimum value.
            There is no specification specified maximum value. Setting maximum allowed value to 1 minute. 
          type: integer
          format: int
          default: 0
          minimum: 0
          maximum: 60000       
        session_attribute:
          description: |-
            This contains the values of the fields to be included in the SESSION_ATTRIBUTE object in the Path Message sent for the LSP.            
          $ref: './rsvpSessionAttribute.yaml#/components/schemas/Rsvp.SessionAttribute'
        tspec:
          description: |-
            This contains the values of the fields to be included in the TSPEC object in the Path Message sent for the LSP.            
          $ref: './rsvpTspec.yaml#/components/schemas/Rsvp.Tspec'
        fast_reroute:
          description: |-
            This contains the values of the fields to be included in the FAST_REROUTE object in the Path Message sent for the LSP. 
            This is an optional object . If this attribute is not included , the FAST_REROUTE object will not be included.           
          $ref: './rsvpFastReroute.yaml#/components/schemas/Rsvp.FastReroute'
        ero:
          description: |-
            This contains the values of the fields to be included in the ERO object in the Path Message sent for the LSP. 
            This is an optional object . If this attribute is not included , the ERO object will not be included.           
          $ref: './rsvpEro.yaml#/components/schemas/Rsvp.Ero'