openapi: 3.1.0

info:
  title: Device endpoint model
  version: 1.0.0

components:
  schemas:
    DeviceEndpoint:
      description: >-
        An endpoint that contains 1..n transmit devices and 1..n receive
        devices.
      type: object
      required: [tx_devices, rx_devices]
      properties:
        tx_devices:
          description: >-
            The unique names of devices that will be transmitting.
          type: array
          items:
            type: string
        rx_devices:
          description: >-
            The unique names of devices that will be receiving.
          type: array
          items:
            type: string

