openapi: 3.1.0

info:
  title: Duration models
  version: 1.0.0

components:
  schemas:
    Flow.Duration:
      description: >-
        A container for different transmit durations. 
      type: object
      properties:
        choice:
          type: string
          enum: [fixed, burst]
        fixed:
          $ref: '#/components/schemas/Flow.Fixed'
        burst:
          $ref: '#/components/schemas/Flow.Burst'

    Flow.Fixed:
      description: >-
        A fixed number of packets will be transmitted after which the flow will stop.
        If the number of packets is set to 0 the flow will not stop.
      type: object      
      properties:
        start_after:
          description: >-
            Start transmit of the flow after a delay of this number of bytes.
          type: integer
          default: 12
          minimum: 2
          maximum: 2000000
        stop_after:
          description: >-
            Stop transmit of the flow after this number of packets.
            A value of 0 means that the flow will not stop transmitting.
          type: integer
          default: 0
           
    Flow.Burst:
      description: >-
        A continuous burst of packets that will not automatically stop.
      type: object      
      properties:
        gap:
          description: >-
            The gap between each burst as a number of bytes.
          type: integer
          minimum: 1
          maximum: 2000000
        burst:
          description: >-
            The number of packets transmitted per burst.
          type: integer
          minimum: 1


