openapi: 3.0.2

info:
  title: Duration data model
  version: 1.0.0

paths: {}

components:
  schemas:
    Continuous:
      type: object
      properties:
        type: 
          type: string
          enum: [continuous]
          default: continuous

    StopAfter:
      type: object      
      properties:
        number_of_packets:
          description: >-
            Stop transmitting after this number of packets has been transmitted
          type: integer
          default: 1
        type: 
          type: string
          enum: [stopAfter]
          default: stopAfter
            
