openapi: 3.1.0

info:
  title: Duration models
  version: ^0.0.0

components:
  schemas:
    Flow.Duration:
      description: >-
        A container for different transmit durations. 
      type: object
      properties:
        choice:
          type: string
          enum: [fixed, burst]
        fixed:
          $ref: '#/components/schemas/Flow.Fixed'
        burst:
          $ref: '#/components/schemas/Flow.Burst'

    Flow.Fixed:
      description: >-
        A fixed number of packets will be transmitted after which the flow will stop.
        If the number of packets is set to 0 the flow will not stop.
      type: object      
      properties:
        packets:
          description: >-
            Stop transmit of the flow after this number of packets.
            A value of 0 means that the flow will not stop transmitting.
          type: integer
          default: 0
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
        delay:
          description: >-
            The delay before starting transmission of packets.
          type: integer
        delay_unit:
          description: >-
            The delay expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]
           
    Flow.Burst:
      description: >-
        A continuous burst of packets that will not automatically stop.
      type: object      
      properties:
        packets:
          description: >-
            The number of packets transmitted per burst.
          type: integer
          minimum: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
        inter_burst_gap:
          description: >-
            The gap between the transmission of each burst.
            A value of 0 means there is no gap between bursts.
          type: integer
        inter_burst_gap_unit:
          description: >-
            The inter burst gap expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]


