openapi: 3.1.0

info:
  title: Traffic flow model
  version: 1.0.0

components:
  schemas:
    Flow:
      description: >- 
        A high level data plane traffic flow.
        A container for endpoint, frame size, frame rate, duration
        and packet headers.
      type: object
      required: [name, endpoint]
      properties:
        name:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        endpoint:
          description: >-
            An endpoint that dictates the type of flow.
          type: object
          required: [choice]
          properties:
            choice:
              description: >-
                Indicates the chosen endpoint
              type: string
              enum: [port_endpoint, device_endpoint]
            port_endpoint:
              $ref: '../ports/endpoint.yaml#/components/schemas/Port.Endpoint'
            device_endpoint:
              $ref: '../devices/endpoint.yaml#/components/schemas/Device.Endpoint'
        packet:
          description: >-
            The packet is a list of traffic protocol headers.
            The order of traffic protocol headers assigned to the list is the
            order they will appear on the wire.
          type: array
          items:
            $ref: './packet-headers/header.yaml#/components/schemas/Header'
        size:
          $ref: './size.yaml#/components/schemas/Size'
        rate:
          description: >-
            The rate of packet transmission
          choice:
            type: string
            enum: [pps, bps, kbps, mbps, gbps, line]
          pps:
            $ref: './rate.yaml#/components/schemas/Pps'
          bps:
            $ref: './rate.yaml#/components/schemas/Bps'
          kbps:
            $ref: './rate.yaml#/components/schemas/Kbps'
          mbps:
            $ref: './rate.yaml#/components/schemas/Mbps'
          gbps:
            $ref: './rate.yaml#/components/schemas/Gbps'
          line:
            $ref: './rate.yaml#/components/schemas/Line'
        duration:
          description: >-
            The duration of packet transmission
          choice:
          - $ref: './duration.yaml#/components/schemas/Continuous'
          - $ref: './duration.yaml#/components/schemas/StopAfter'

        
      
