openapi: 3.1.0

info:
  title: Traffic flow model
  version: 1.0.0

components:
  schemas:
    Flow:
      description: >- 
        A high level data plane traffic flow.
        A container for endpoint, frame size, frame rate, duration
        and packet headers.
      type: object
      required: [name, endpoint]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        endpoint:
          description: >-
            An endpoint that dictates the type of flow.
          type: object
          required: [choice]
          properties:
            choice:
              description: >-
                The type of endpoint that the traffic will be based on.
              type: string
              enum: [port, device]
            port:
              $ref: './port-endpoint.yaml#/components/schemas/Flow.PortEndpoint'
            device:
              $ref: './device-endpoint.yaml#/components/schemas/Flow.DeviceEndpoint'
        packet:
          description: >-
            The packet is a list of traffic protocol headers.
            The order of traffic protocol headers assigned to the list is the
            order they will appear on the wire.
          type: array
          items:
            $ref: './packet-headers/header.yaml#/components/schemas/Flow.Header'
        size:
          $ref: './size.yaml#/components/schemas/Flow.Size'
        rate:
          $ref: './rate.yaml#/components/schemas/Flow.Rate'
        # duration:
        #   description: >-
        #     The duration of packet transmission
        #   choice:
        #   - $ref: './duration.yaml#/components/schemas/StopAfter'

        
      
