openapi: 3.1.0

info:
  title: Flow model
  version: 1.0.0

components:
  schemas:
    Flow.Flow:
      description: >- 
        A high level data plane traffic flow.
        Acts as a container for endpoints, frame size, frame rate, duration
        and packet headers.
      type: object
      required: [name, endpoint]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        endpoint:
          $ref: './endpoint.yaml#/components/schemas/Flow.Endpoint'
        packet:
          description: >-
            The packet is a list of traffic protocol headers.
            The order of traffic protocol headers assigned to the list is the
            order they will appear on the wire.
          type: array
          items:
            $ref: './packet-headers/header.yaml#/components/schemas/Flow.Header'
        size:
          $ref: './size.yaml#/components/schemas/Flow.Size'
        rate:
          $ref: './rate.yaml#/components/schemas/Flow.Rate'
        duration:
          $ref: './duration.yaml#/components/schemas/Flow.Duration'
        state:
          description: >-
            Set the configured state of the flow.
            Use the /results API to get the actual state of the flow.
          type: string
          enum: [start, stop, pause, resume]
     
      
