openapi: 3.1.0

info:
  title: Port endpoint model
  version: 1.0.0

components:
  schemas:
    Flow.PortEndpoint:
      description: >-
        An endpoint that contains a transmit port and 0..n receive ports.
      type: object
      required: [tx_port]
      properties:
        tx_port:
          description: >-
            The unique name of a port that is the transmit port.
          type: string
        rx_ports:
          description: >-
            The unique names of ports that are the intended receive ports.
          type: array
          items:
            type: string
        tx_patterns:
          description: >-
            A list of custom patterns that will be applied to the transmit port.
          type: array
          items:
            $ref: './port-pattern.yaml#/components/schemas/Flow.PortPattern'
