openapi: 3.1.0

info:
  title: Port pattern model
  version: 1.0.0

components:
  schemas:
    PortPattern:
      description: >-
        A pattern that is applied to a test port.
        The name of the pattern will be reflected in the port results.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        offset:
          type: integer
          description: >-
            The offset from the beginning of the packet
        pattern:
          type: string
          description: >-
            The value of the pattern
        mask:
          type: string
          description: >-
            The mask value to be applied against the pattern
