openapi: 3.0.2

info:
  title: Rate data model
  version: 1.0.1
  
paths: {}

components:
  schemas:
    Flow.Rate:
      type: object
      description: >-
        The rate of packet transmission
      required: [unit, value]
      properties:
        unit:
          description: >-
            The value is a unit of this.
          type: string
          enum: [pps, bps, kbps, mbps, gbps, line]
        value:
          description: >-
            The actual rate.
          type: integer
        gap:
          description: >-
            The minimum gap in bytes between packets.
          type: integer
          minimum: 8
          maximum: 258

