openapi: 3.0.2

info:
  title: Rate data model
  version: 1.0.0
  
paths: {}

components:
  schemas:
    Pps:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [pps]
          default: pps

    Bps:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [bps]
          default: bps

    Kbps:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [kbps]
          default: kbps

    Mbps:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [mbps]
          default: mbps

    Gbps:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [gbps]
          default: gbps

    Line:
      type: object
      required: [type, value]  
      properties:
        value:
          type: number
          default: 1
        type:
          type: string
          enum: [line]
          default: line

        
