openapi: 3.0.2

info:
  title: Rate data model
  version: 1.0.0
  
paths: {}

components:
  schemas:
    Flow.Rate:
      type: object
      description: >-
        The rate of packet transmission
      required: [type, value]
      properties:
        type:
          type: string
          enum: [pps, bps, kbps, mbps, gbps, line]
        value:
          type: number
