openapi: 3.0.2

info:
  title: Frame size models
  version: 1.0.0

paths: {}

components:
  schemas:
    Flow.Size:
      description: >-
        The frame size which overrides the total length of the packet
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [fixed, increment, random]
        fixed:
          type: integer
          default: 64
        increment:
          $ref: '#/components/schemas/Flow.Size.Increment'
        random:
          $ref: '#/components/schemas/Flow.Size.Random'
          
    Flow.Size.Increment:
      type: object
      description: >-
        Frame size that increments from a starting size to 
        an ending size incrementing by a step size
      required: [start, end, step]
      properties:
        start:
          description: Starting frame size in bytes
          type: integer
          minimum: 1
          default: 64
        end:
          description: Ending frame size in bytes
          type: integer
          minimum: 64
          default: 1518
        step:
          description: Step frame size in bytes
          type: integer
          default: 1

    Flow.Size.Random:
      type: object
      description: >-
        Random frame size
      required: [min, max]
      properties:
        min:
          type: integer
          default: 64
        max:
          type: integer
          default: 1518

