openapi: 3.1.0

info:
  title: Layer1 models
  version: ^0.0.0

components:
  schemas:
    Layer1.Layer1:
      description: >-
        A container for layer1 ports and settings.
      type: object
      required: [name, choice]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_names:
          description: >- 
            A list of unique names of a port objects that will share the 
            choice settings. 
          type: array
          items:
            type: string
        choice:
          description: >-
            The type of layer1 characteristics.
          type: string
          enum: [one_hundred_gbe, ethernet]
        one_hundred_gbe:
          $ref: '#/components/schemas/Layer1.OneHundredGbe'
        ethernet:
          $ref: '#/components/schemas/Layer1.Ethernet'

    Layer1.OneHundredGbe:
      description: >-
        100 gigabit ethernet settings
      type: object
      properties:
        ieee_media_defaults:
          description: >-
            Enable/disable ieee media default settings.
            True will override the speed, auto_negotiate, link_training, rs_fec settings.
          type: boolean
          default: true
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: false
        link_training:
          description: >-
            Enable/disable link training.
          type: boolean
          default: false
        rs_fec:
          description: >-
            Enable/disable reed solomon forward error correction (RS FEC).
          type: boolean
          default: false
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [one_hundred_gbps, fifty_gbps, forty_gbps, twenty_five_gpbs, ten_gbps]
          default: one_hundred_gbps
        pfc:
          $ref: '#/components/schemas/Layer1.Pfc'
    
    Layer1.Ethernet:
      description: >-
        10/100/1000 Ethernet settings
      type: object
      properties:
        media:
          type: string
          enum: [copper, fiber]
          default: copper
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [one_thousand_mbps, one_hundred_fd_mbps, one_hundred_hd_mbps, ten_fd_mbps, ten_hd_mbps]
          default: one_thousand_mbps
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: true
        advertise_one_thousand_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_one_hundred_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_one_hundred_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_ten_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_ten_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        pfc:
          $ref: '#/components/schemas/Layer1.Pfc'

    Layer1.Pfc:
      description: >-
        Priority flow control settings
      type: object
      properties:
        flow_control_type:
          description: >-
            The type of priority flow control.
            If ieee_802_3x is selected then none of the pfc properties will apply.
          type: string
          enum: [ieee_802_1qbb, ieee_802_3x]
        pfc_delay_quanta:
          type: integer
        pfc_class_0:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_1:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_2:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_3:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_4:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_5:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_6:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_7:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer

