openapi: 3.1.0

info:
  title: State models
  version: 1.0.0

components:
  schemas:
    ConfigState:
      description: >-
        placeholder
      type: object
      required: [state]
      properties:
        state:
          type: string
          enum: [CREATE, UPDATE]
        ports:
          type: array
          items:
            $ref: '../port/port.yaml#/components/schemas/Port'
        devices:
          type: array
          items:
            $ref: '../device/device-group.yaml#/components/schemas/DeviceGroup'
        flows:
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow'

    TrafficState:
      description: >-
        placeholder
      type: object
      required: [requested_state]
      properties:
        requested_state:
          type: string
          enum: [START_TX, STOP_TX, PAUSE_TX]
        flows:
          description: >-
            The names of flow objects.
          type: array
          items:
            type: string

    CaptureState:
      description: >-
        placeholder
      type: object
      required: [requested_state]
      properties:
        requested_state:
          type: string
          enum: [START, STOP]
        captures:
          description: >-
            The names of capture objects.
          type: array
          items:
            type: string

    DesiredState:
      description: >-
        The desired state of the traffic generator 
      type: object
      properties:
        configuration:
          $ref: '#/components/schemas/ConfigState'
        traffic:
          $ref: '#/components/schemas/TrafficState'
        capture:
          $ref: '#/components/schemas/CaptureState'

    ActualState:
      description: >-
        The desired and actual state of the traffic generator
      type: object
      properties:
        states:
          type: string
          enum: [CONFIG, FLOW, CAPTURE]
        traffic:
          description: >-
            A list of configured flow names
            If the list is empty the type will apply to all configured flows
          type: array
          items:
            type: string
        capture:
            type: integer
            description: >-
              The number of seconds to wait for all the flows to be in the specified state
