openapi: 3.1.0

info:
  title: State models
  version: 1.0.0

components:
  schemas:
    State.Config:
      description: >-
        placeholder
      type: object
      required: [state]
      properties:
        state:
          description: >-
            The requested state to be applied to the current configuration.
          type: string
          enum: [CREATE, UPDATE, DELETE]
        ports:
          description: >-
            The port content to be used by the requested state.
          type: array
          items:
            $ref: '../port/port.yaml#/components/schemas/Port.Port'
        devices:
          type: array
          items:
            $ref: '../device/device-group.yaml#/components/schemas/Emulated.DeviceGroup'
        flows:
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow.Flow'

    State.Flow:
      description: >-
        Request for the traffic generator to move flows to a specific state.
      type: object
      required: [state]
      properties:
        state:
          description: >-
            The requested state of the flows.
          type: string
          enum: [START, STOP, PAUSE]
        flows:
          description: >-
            The unique names of flow objects.
          type: array
          items:
            type: string

    State.Port:
      description: >-
        Request for the traffic generator to move ports to a specific state.
      type: object
      required: [state]
      properties:
        state:
          description: >-
            The requested state of the port.
          type: string
          enum: [LINK_UP, LINK_DOWN]
        flows:
          description: >-
            The unique names of port objects.
          type: array
          items:
            type: string

    State.Capture:
      description: >-
        placeholder
      type: object
      required: [requested_state]
      properties:
        requested_state:
          type: string
          enum: [START, STOP]
        captures:
          description: >-
            The names of capture objects.
          type: array
          items:
            type: string

    State.Desired:
      description: >-
        The desired state of the traffic generator 
      type: object
      properties:
        configuration:
          $ref: '#/components/schemas/State.Config'
        traffic:
          $ref: '#/components/schemas/State.Flow'
        capture:
          $ref: '#/components/schemas/State.Capture'

    State.Actual:
      description: >-
        The desired and actual state of the traffic generator
      type: object
      properties:
        states:
          type: string
          enum: [CONFIG, FLOW, CAPTURE]
        flow:
          description: >-
            A list of configured flow names
            If the list is empty the type will apply to all configured flows
          type: array
          items:
            type: string
        capture:
            type: integer
            description: >-
              The number of seconds to wait for all the flows to be in the specified state
