openapi: 3.1.0

info:
  title: Configuration models
  version: 1.0.0

components:
  schemas:
    Config.Config:
      description: >-
        A container for all models that are part of the configuration.
      type: object
      properties:
        ports:
          description: >-
            The ports that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../port/port.yaml#/components/schemas/Port.Port'
        device_groups:
          description: >-
            The device groups that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../device/device-group.yaml#/components/schemas/Device.DeviceGroup'
        flows:
          description: >-
            The flows that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow.Flow'
        layer1:
          description: >-
            The layer1 settings that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../port/layer1.yaml#/components/schemas/Port.Layer1'
        captures:
          description: >-
            The captures that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../capture/capture.yaml#/components/schemas/Capture.Capture'

