openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Control.PortLink:
      description: >-
        Control port link state
      type: object
      properties:
        port_names:
          description: >-
            The names of port objects to.
            An empty list will control all port objects.
          type: array
          items:
            type: string
        state:
          description: >-
            The link state.
          type: string
          enum: [up, down]

    Control.FlowTransmit:
      description: >-
        Control flow transmit state
      type: object
      properties:
        flow_names:
          description: >-
            The names of flow objects to control.
            An empty list will control all flow objects.
          type: array
          items:
            type: string
        state:
          description: >-
            The transmit state.
          type: string
          enum: [start, stop, pause]

