openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Control.PortLink:
      description: >-
        Control link state
      type: object
      properties:
        names:
          description: >-
            The names of port objects to control link state.
            An empty list will control all port objects.
          type: array
          items:
            type: string
        state:
          description: >-
            The state of the port link
          type: string
          enum: [up, down]


