openapi: 3.1.0

info:
  title: Layer1 models
  version: ^0.0.0

components:
  schemas:
    Port.Layer1:
      description: >-
        A container for layer1 ports and settings.
      type: object
      required: [name, choice]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_names:
          description: >- 
            A list of unique names of a port objects that will share the 
            choice settings. 
          type: array
          items:
            type: string
        choice:
          description: >-
            The type of layer1 characteristics.
          type: string
          enum: [one_hundred_gbe, ethernet]
        one_hundred_gbe:
          $ref: '#/components/schemas/Port.OneHundredGbe'
        ethernet:
          $ref: '#/components/schemas/Port.Ethernet'

    Port.OneHundredGbe:
      description: >-
        100 gigabit ethernet settings
      type: object
      properties:
        ieee_media_defaults:
          description: >-
            Enable/disable ieee media default settings.
            True will override the speed, auto_negotiate, link_training, rs_fec settings.
          type: boolean
          default: true
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: false
        link_training:
          description: >-
            Enable/disable link training.
          type: boolean
          default: false
        rs_fec:
          description: >-
            Enable/disable reed solomon forward error correction (RS FEC).
          type: boolean
          default: false
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [one_hundred_gbps, fifty_gbps, forty_gbps, twenty_five_gpbs, ten_gbps]
          default: one_hundred_gbps
    
    Port.Ethernet:
      description: >-
        10/100/1000 Ethernet settings
      type: object
      properties:
        media:
          type: string
          enum: [copper, fiber]
          default: copper
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [one_thousand_mbps, one_hundred_fd_mbps, one_hundred_hd_mbps, ten_fd_mbps, ten_hd_mbps]
          default: one_thousand_mbps
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: true
        advertise_one_thousand_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_one_hundred_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_one_hundred_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_ten_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_ten_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
