openapi: 3.1.0

info:
  title: Port model
  version: 1.0.0

components:
  schemas:
    Port.Port:
      description: >-
        An abstract test port used to associate a unique name with the location
        of a physical or virtual test location.

        Some different types of test locations are:
          - physical appliance with multiple ports
          - physical chassis with multiple cards and ports
          - local interface
          - virtual machine
          - docker container
      type: object
      required: [name, location]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        location:
          $ref: '#/components/schemas/Port.Location'
    
    Port.Location:
      description: >-
        The location of a test resource.
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [physical, interface, virtual, container]
        physical:
          $ref: '#/components/schemas/Port.Physical'
        interface:
          $ref: '#/components/schemas/Port.Interface'
        virtual:
          $ref: '#/components/schemas/Port.Virtual'
        container:
          $ref: '#/components/schemas/Port.Container'

    Port.Physical:
      description: >-
        A physical test port
      type: object
      required: [address, port]
      properties:
        address:
          type: string
        board:
          type: number
          default: 1
        port:
          type: number
          default: 1
        fanout:
          type: number
          default: null

    Port.Interface:
      description: >-
        An interface test port
      type: object
      required: [name]
      properties:
        name:
          type: string

    Port.Virtual:
      description: >-
        A virtual test port
      type: object
      required: [address]
      properties:
        address:
          type: string

    Port.Container:
      description: >-
        A container test port
      type: object
      required: [address, port]
      properties:
        address:
          type: string
        port:
          type: number

