openapi: 3.1.0

info:
  title: Port models
  version: 1.0.0

components:
  schemas:
    Port.Port:
      description: >-
        An abstract test port.
      type: object
      required: [name, location]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        location:
          description: >- 
            The location of a test port. 
            It is the endpoint where packets will emit from.

            Test port locations can be the following:
              - physical appliance with multiple ports
              - physical chassis with multiple cards and ports
              - local interface
              - virtual machine, docker container, kubernetes cluster

            The test port location format is implementation specific.
            Use the /results API to determine what formats the implementation 
            supports for the location property.
          type: string
        link_state:
          description: >- 
            The configured link state of the port.
            Compare the actual state vs the configured state by using the 
            /results API.
          type: string
          enum: [up, down]
          default: up
        capture_state:
          description: >- 
            The configured capture state of the port.
            Compare the actual state vs the configured state by using the 
            /results API.
          type: string
          enum: [started, stopped]
          default: stopped

