openapi: 3.1.0

info:
  title: Fragments
  version: 1.0.1
  description: >-
    This file should be used as a repository for fragments that will be used
    as a direct inline replacement where ever the keyword is found
    
components:
  x-inline:
    description: -> 
      Fragment to be used in properties that will be replaced by the 
      pre-processor.
    UniqueName:
      description: >-
        Unique name of an object that is the primary key for objects found in 
        arrays.
      type: string
      pattern: ^[\sa-zA-Z0-9-_()><\[\]]+$

