openapi: 3.1.0

info:
  title: Arp packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Arp:
      description: ARP packet header
      type: object
      properties:
        hardware_type:
          description: >-
            Network link protocol type. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol_type:
          description: >-
            The internetwork protocol for which the ARP request is intended. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        hardware_length:
          description: >-
            Length (in octets) of a hardware address. 
            Max length is 1 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol_length:
          description: >-
            Length (in octets) of internetwork addresses. 
            Max length is 1 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        operation:
          description: >-
            The operation that the sender is performing: 1 for request, 2 for reply.
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        sender_hardware_addr:
          description: >-
            Media address of the sender.
            Max length is 6 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        sender_protocol_addr:
          description: >-
            Internetwork address of the sender.
            Max length is 4 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        target_hardware_addr:
          description: >-
            Media address of the target.
            Max length is 6 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        target_protocol_addr:
          description: >-
            Internetwork address of the target.
            Max length is 4 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
 