openapi: 3.1.0

info:
  title: Bit pattern models
  version: ^0.0.0

components:
  schemas:
    Flow.BitPattern:
      description: >-
        Container for a bit pattern
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [bitlist, bitcounter]
        bitlist:
          $ref: '#/components/schemas/Flow.BitList'
        bitcounter:
          $ref: '#/components/schemas/Flow.BitCounter'

    Flow.BitList:
      type: object
      description: >-
        A pattern which is a list of values.
      properties:
        offset:
          description: >-
            Bit offset in the packet at which the pattern will be applied
          type: integer
          minimum: 1
          default: 1
        length:
          description: >-
            The number of bits in the packet that the pattern will span
          type: integer
          minimum: 1
          default: 1
        count:
          type: integer
          description: >-
            The number of values to generate before repeating
          default: 1
        values:
          type: array
          items:
            description: >-
              The value that the packet offset to offset + length will be
              either incremented or decremented by.
              If the value is greater than the length it will be truncated.
            type: string
            pattern: '^[A-Fa-f0-9: ]+$'

    Flow.BitCounter:
      type: object
      description: >-
        An incrementing pattern
      properties:
        offset:
          description: >-
            Bit offset in the packet at which the pattern will be applied
          type: integer
          minimum: 0
          default: 0
        length:
          description: >-
            The number of bits in the packet that the pattern will span
          type: integer
          minimum: 1
          default: 32
        count:
          type: integer
          description: >-
            The number of values to generate before repeating
            A value of 0 means the pattern will count continuously
          minimum: 1
          default: 1
        start:
          description: >-
            The starting value of the pattern.
            If the value is greater than the length it will be truncated.
          type: string
          pattern: '^[A-Fa-f0-9: ]+$'
          default: 0
        step:
          description: >-
            The amount the start value will be incremented by
            If the value is greater than the length it will be truncated.
          type: string
          pattern: '^[A-Fa-f0-9: ]+$'
          default: 0


