openapi: 3.1.0

info:
  title: Custom packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Custom:
      type: object
      description: Custom packet header
      required: [bytes]
      properties:
        bytes:
          description: >-
            A custom packet header defined as a string of hex bytes.
            The string MUST contain valid hex characters.
            Spaces or colons can be part of the bytes but will be discarded
            This can be used to create a custom protocol from other inputs 
            such as scapy, wireshark, pcap etc.

            An example of ethernet/ipv4:
            '00000000000200000000000108004500001400010000400066e70a0000010a000002'
          type: string
          pattern: '^[A-Fa-f0-9: ]+$'
        patterns:
          description: >-
            Modify the bytes with bit based patterns
          type: array
          items:
            $ref: './bitpatterns.yaml#/components/schemas/Flow.BitPattern'

