openapi: 3.1.0

info:
  title: Ethernet traffic packet header
  version: 1.0.0

components:
  schemas:
    Flow.Ethernet:
      description: Ethernet packet header
      type: object
      properties:
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        ether_type:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'


    
