openapi: 3.1.0

info:
  title: Ethernet traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Ethernet:
      description: Ethernet packet header
      type: object
      properties:
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ether_type:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pfc_queue:
          description: >-
            Optional field of 3 bits
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'

    
