openapi: 3.1.0

info:
  title: Ethernet traffic packet header
  version: 1.0.0

components:
  schemas:
    Flow.Ethernet:
      description: Ethernet packet header
      type: object
      properties:
        dst:
          description: >-
            Destination mac address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        src:
          description: >-
            Source mac address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        ether_type:
          description: >-
            The type of encapsulated ethernet protocol
            Values of 1500 and below indicate the size of the payload in octets
            Values of 1536 and above indicates which protocol is encapsulated in the payload of the frame
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'


    
