openapi: 3.0.2

info:
  title: Protocols data model
  version: 1.0.1

paths: {}

components:
  schemas:
    Flow.GroupBy:
      type: object
      description: >-
        Group results 
      required: [field, label]
      properties:
        field: 
          type: string
        label:
          type: string


