openapi: 3.1.0

info:
  title: Packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Header:
      description: >-
        Container for all traffic packet headers
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [custom, ethernet, vlan, ipv4, pfcpause]
        custom:
          $ref: './custom.yaml#/components/schemas/Flow.Custom'
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Flow.Ethernet'
        vlan:
          $ref: './vlan.yaml#/components/schemas/Flow.Vlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Flow.Ipv4'
        pfcpause:
          $ref: './pfcpause.yaml#/components/schemas/Flow.PfcPause'
        group_by:
          type: array
          items:
            $ref: './groupby.yaml#/components/schemas/Flow.GroupBy'
