openapi: 3.1.0

info:
  title: ICMP packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Icmp:
      description: >-
        ICMP packet header
      type: object
      properties:
        type:
          description: >-
            ICMP type. Max length is 1 byte.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        code:
          description: >-
            ICMP subtype. Max length is 1 byte.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        checksum:
          description: >-
            Internet checksum for error checking, 
            calculated from the ICMP header and data 
            with value 0 substituted for this field.
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        rest_of_headers:
          description: >-
            Contents vary based on the ICMP type and code.  Max length is 4 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
    
 