openapi: 3.1.0

info:
  title: Ipv4 ip priority models
  version: 1.0.0

components:
  schemas:
    Flow.Ipv4.Priority:
      description: >-
        Ipv4 ip priority that can be one of RAW or DSCP.
      type: object
      x-constants:
        PRIORITY_RAW: 0
      required: [choice]
      properties:
        choice:
          type: string
          enum: [dscp, raw]
        dscp:
          $ref: '#/components/schemas/Flow.Ipv4.Dscp'
        raw: 
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'

    Flow.Ipv4.Dscp:
      description: >-
        Differentiated services code point (DSCP) packet field.

        PHB (per-hop-behavior) value is 6 bits: >=0 PHB <=63.
        ECN (explicit-congestion-notification) value is 2 bits: >=0 ECN <=3
      type: object
      x-constants:
        PHB_DEFAULT: 0
        PHB_CS1: 8
        PHB_CS2: 16
        PHB_CS3: 24
        PHB_CS4: 32
        PHB_CS5: 40
        PHB_CS6: 48
        PHB_CS7: 56
        PHB_EF46: 46
        PHB_AF11: 10
        PHB_AF12: 12
        PHB_AF13: 14
        PHB_AF21: 18
        PHB_AF22: 20
        PHB_AF23: 22
        PHB_AF31: 26
        PHB_AF32: 28
        PHB_AF33: 30
        PHB_AF41: 24
        PHB_AF42: 36
        PHB_AF43: 38
        ECN_NON_CAPABLE: 0
        ECN_CAPABLE_TRANSPORT_0: 1
        ECN_CAPABLE_TRANSPORT_1: 2
        ECN_CONGESTION_ENCOUNTERED: 3
      properties:
        phb: 
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ecn: 
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
