openapi: 3.1.0

info:
  title: Ipv4 packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Ipv4:
      description: Ipv4 packet header
      type: object
      properties:
        priority:
          type: object
          required: [choice]
          properties:
            choice:
              type: string
              enum: [dscp, tos, raw]
            dscp:
              $ref: './ipv4.priority.yaml#/components/schemas/Flow.Ipv4.Dscp'
            tos:
              $ref: './ipv4.priority.yaml#/components/schemas/Flow.Ipv4.Tos'
            raw:
              $ref: './ipv4.priority.yaml#/components/schemas/Flow.Ipv4.Raw'
        src:
          description: >-
            Ipv4 source address
          x-fld-offset: 96
          x-fld-length: 32
          x-fld-default: 0.0.0.0
          oneOf:
          - type: string
          - type: integer
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        dst:
          description: >-
            Ipv4 destination address
          x-fld-offset: 128
          x-fld-length: 32
          x-fld-default: 0.0.0.0
          oneOf:
          - type: string
          - type: integer
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        type:
          description: >-
            Indicates to the server the type of protocol header
          type: string
          enum: [ipv4]
          default: ipv4
              
