openapi: 3.1.0

info:
  title: Dscp packet field model
  version: 1.0.0

components:
  schemas:
    Flow.Ipv4.Dscp:
      description: >-
        Differentiated services code point (DSCP) packet field.
        DSCP value constraint is 6 bits. >=0 <=63
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [enum, list]
        enum:
          type: string
          enum:
          - PHB_DEFAULT_0
          - PHB_CS1_8
          - PHB_CS2_16
          - PHB_CS3_24
          - PHB_CS4_32
          - PHB_CS5_40
          - PHB_CS6_48
          - PHB_CS7_56
          - PHB_EF46_46
          - PHB_AF11_10
          - PHB_AF12_12
          - PHB_AF13_14
          - PHB_AF21_18
          - PHB_AF22_20
          - PHB_AF23_22
          - PHB_AF31_26
          - PHB_AF32_28
          - PHB_AF33_30
          - PHB_AF41_24
          - PHB_AF42_36
          - PHB_AF43_38
        list:
          type: array
          items: 
            type: string
        ecn:
          $ref: '#/components/schemas/Flow.Ipv4.Ecn'

    Flow.Ipv4.Ecn:
      description: >-
        Explicit congestion notification (ECN) packet field.
        ECN value constraint is 2 bits. >=0 <=3
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [enum, list]
        enum:
          type: string
          enum:
          - ECN_NON_CAPABLE_00
          - ECN_CAPABLE_01
          - ECN_CAPABLE_10
          - ECN_CONGESTION_ENCOUNTERED_11
        list:
          type: array
          items: 
            type: string

    Flow.Ipv4.Raw:
      description: >-
        Raw ip priority
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [string, list]
        string:
          type: string
        list:
          type: array
          items:
            type: string
      