openapi: 3.1.0

info:
  title: Ipv4 packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Ipv4:
      description: Ipv4 packet header
      type: object
      properties:
        priority:
          $ref: './ipv4-priority.yaml#/components/schemas/Flow.Ipv4.Priority'
        src:
          $ref: './patterns.yaml#/components/schemas/StringPattern'
        dst:
          $ref: './patterns.yaml#/components/schemas/StringPattern'
