openapi: 3.1.0

info:
  title: Ipv4 packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Ipv4:
      description: Ipv4 packet header
      type: object
      properties:
        priority:
          description: >-
            Ipv4 ip priority that can be one of TOS, RAW or DSCP.
          type: object
          required: [choice]
          properties:
            choice:
              type: string
              enum: [dscp, raw]
            dscp:
              $ref: './ipv4.priority.yaml#/components/schemas/Flow.Ipv4.Dscp'
            raw:
              $ref: './ipv4.priority.yaml#/components/schemas/Flow.Ipv4.Raw'
        src:
          description: >-
            Ipv4 source address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        dst:
          description: >-
            Ipv4 destination address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
