openapi: 3.1.0

info:
  title: Protocol field patterns
  version: 1.0.0

components:
  schemas:
    Random:
      type: object
      description: >-
        A non repeatable random pattern
      required: [type]
      properties:
        type:
          type: string
          enum: [random]
          default: random

    ValueList:
      type: object
      description: >-
        A list of values. 
        The number of values in the list defines the count.
      required: [type]
      properties:
        values:
          type: array
          items:
            type: string
        type:
          type: string
          enum: [list]
          default: list

    Counter:
      type: object
      description: >-
        A pattern that can increment or decrement for a specific number of times
      required: [type, start, step]
      properties:
        start:
          type: string
          description: >-
            The start value will be incremented or decremented by this step value.
        step:
          type: string
          description: >-
            The start value will be incremented or decremented by this step value.
        count:
          type: integer
          default: 2
          description: >-
            The number of values to generate before repeating the pattern.
        type:
          type: string
          enum: [counter]
          default: counter



