openapi: 3.1.0

info:
  title: Packet header pattern models
  version: 1.0.0

components:
  schemas:
    Flow.Pattern:
      description: >-
        A container for packet header field patterns.
        Possible patterns are fixed, list, increment, decrement, random.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, increment, decrement, random]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        increment:
          $ref: '#/components/schemas/Flow.Increment'
        decrement:
          $ref: '#/components/schemas/Flow.Decrement'
        random:
          $ref: '#/components/schemas/Flow.Random'

    Flow.Increment:
      description: >-
        An incrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string
        count: 
          type: number
    
    Flow.Decrement:
      description: >-
        A decrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string
        count: 
          type: number

    Flow.Random:
      description: >-
        A repeatable random range pattern.
      type: object
      properties:
        min:
          type: string
        max:
          type: string
        step: 
          type: number
        seed:
          type: string
        count: 
          type: number
