openapi: 3.1.0

info:
  title: Packet header pattern models
  version: 1.0.0

components:
  schemas:
    StringPattern:
      description: >-
        A string pattern
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, counter]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        counter:
          type: object
          properties:
            start:
              type: string
            step:
              type: string
            direction:
              type: string
              enum: [increment, decrement]
            count: 
              type: number

    NumberPattern:
      description: >-
        A string pattern
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, counter]
        fixed:
          type: number
        list:
          type: array
          items:
            type: number
        counter:
          type: object
          properties:
            start:
              type: number
            step:
              type: number
            direction:
              type: string
              enum: [increment, decrement]
            count: 
              type: number
