openapi: 3.1.0

info:
  title: Packet header pattern models
  version: 1.0.1

components:
  schemas:
    Flow.Pattern:
      description: >-
        A container for packet header field patterns.
        Possible patterns are fixed, list, counter, random.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, counter, random]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        counter:
          $ref: '#/components/schemas/Flow.Counter'
        random:
          $ref: '#/components/schemas/Flow.Random'

    Flow.Counter:
      description: >-
        A counter pattern that can increment or decrement.
      type: object
      properties:
        start:
          description: >-
            The value at which the pattern will start.
          type: string
        step:
          description: >-
            The value at which the pattern will increment or decrement by.
          type: string
        count: 
          description: >-
            The number of values in the pattern.
          type: number
        up:
          description: >-
            Determines whether the pattern will increment (true) or decrement (false).
          type: boolean
          default: true
    
    Flow.Random:
      description: >-
        A repeatable random range pattern.
      type: object
      properties:
        min:
          type: string
        max:
          type: string
        step: 
          type: number
        seed:
          type: string
        count: 
          type: number
