openapi: 3.1.0

info:
  title: Pfc Pause packet header model
  version: 1.0.0

components:
  schemas:
    Flow.PfcPause:
      description: PFC Pause packet header
      type: object
      required: [type]
      properties:
        dst:
          description: >-
            Destination mac address
          x-fld-offset: 0
          x-fld-length: 48
          x-fld-default: 00:00:00:00:00:00
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        src:
          description: >-
            Source mac address
          x-fld-offset: 48
          x-fld-length: 48
          x-fld-default: 00:00:00:00:00:00
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        ether_type:
          description: >-
            The type of encapsulated ethernet protocol
            Values of 1500 and below indicate the size of the payload in octets
            Values of 1536 and above indicates which protocol is encapsulated in the payload of the frame
          x-fld-offset: 96
          x-fld-length: 16
          x-fld-default: 0x8808
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        control_op_code:
          description: >-
            The control op code
          x-fld-offset: 112
          x-fld-length: 16
          x-fld-default: 0x0101
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        priority_enable_vector:
          description: >-
            The priority enable vector
          x-fld-offset: 128
          x-fld-length: 16
          x-fld-default: 0x0001
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_0:
          description: >-
            The pause quanta pfc queue 0
          x-fld-offset: 144
          x-fld-length: 16
          x-fld-default: 0xffff
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_1:
          description: >-
            The pause quanta pfc queue 1
          x-fld-offset: 160
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_2:
          description: >-
            The pause quanta pfc queue 2
          x-fld-offset: 176
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_3:
          description: >-
            The pause quanta pfc queue 3
          x-fld-offset: 192
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_4:
          description: >-
            The pause quanta pfc queue 4
          x-fld-offset: 208
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_5:
          description: >-
            The pause quanta pfc queue 5
          x-fld-offset: 224
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_6:
          description: >-
            The pause quanta pfc queue 6
          x-fld-offset: 240
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        pfc_queue_7:
          description: >-
            The pause quanta pfc queue 7
          x-fld-offset: 256
          x-fld-length: 16
          x-fld-default: 0x0000
          oneOf:
          - type: integer
          - type: string
          - $ref: '#/components/schemas/ValueList'
          - $ref: '#/components/schemas/Counter'
          - $ref: '#/components/schemas/Random'
        type:
          description: >-
            The type of packet header
          type: string
          enum: [pfcpause]
          default: pfcpause


    
