openapi: 3.1.0

info:
  title: Pfc Pause packet header model
  version: 1.0.0

components:
  schemas:
    Flow.PfcPause:
      description: PFC Pause packet header
      type: object
      properties:
        dst:
          description: >-
            Destination mac address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        src:
          description: >-
            Source mac address
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        ether_type:
          description: >-
            The type of encapsulated ethernet protocol
            Values of 1500 and below indicate the size of the payload in octets
            Values of 1536 and above indicates which protocol is encapsulated in the payload of the frame
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        control_op_code:
          description: >-
            The control op code
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        priority_enable_vector:
          description: >-
            The priority enable vector
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_0:
          description: >-
            The pause quanta pfc queue 0
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_1:
          description: >-
            The pause quanta pfc queue 1
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_2:
          description: >-
            The pause quanta pfc queue 2
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_3:
          description: >-
            The pause quanta pfc queue 3
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_4:
          description: >-
            The pause quanta pfc queue 4
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_5:
          description: >-
            The pause quanta pfc queue 5
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_6:
          description: >-
            The pause quanta pfc queue 6
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        pfc_queue_7:
          description: >-
            The pause quanta pfc queue 7
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'


    
