openapi: 3.1.0

info:
  title: Pfc Pause packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.PfcPause:
      description: >-
        IEEE 802.1Qbb PFC Pause packet header.
        - dst: 01:80:C2:00:00:01 48bits
        - src: 48bits 
        - ether_type: 0x8808 16bits
        - control_op_code: 0x0101 16bits
        - class_enable_vector: 16bits
        - pause_class_0: 0x0000 16bits
        - pause_class_1: 0x0000 16bits
        - pause_class_2: 0x0000 16bits
        - pause_class_3: 0x0000 16bits
        - pause_class_4: 0x0000 16bits
        - pause_class_5: 0x0000 16bits
        - pause_class_6: 0x0000 16bits
        - pause_class_7: 0x0000 16bits
      type: object
      properties:
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ether_type:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        control_op_code:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        class_enable_vector:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_0:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_1:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_2:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_3:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_4:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_5:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_6:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pause_class_7:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'


    
