openapi: 3.1.0

info:
  title: Pfc Pause packet header model
  version: 1.0.0

components:
  schemas:
    Flow.PfcPause:
      description: PFC Pause packet header
      type: object
      properties:
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        ether_type:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        control_op_code:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        priority_enable_vector:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_0:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_1:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_2:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_3:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_4:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_5:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_6:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        pfc_queue_7:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'


    
