openapi: 3.1.0

info:
  title: Tcp packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Tcp:
      description: Tcp packet header
      type: object
      properties:
        src_port:
          description: >-
            Tcp source port. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        dst_port:
          description: >-
            Tcp destination port. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        seq_num:
          description: >-
            Tcp Sequence Number.
            Max length is 4 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ack_num:
          description: >-
            Tcp Acknowledgement Number.
            Max length is 4 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        data_offset:
          description: >-
            The number of 32 bit words in the TCP header.  This indicates where the data begins.
            Max length is 4 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ecn_ns:
          description: >-
            Explicit congestion notification, concealment protection.
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ecn_cwr:
          description: >-
            Explicit congestion notification, congestion window reduced.
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ecn_echo:
          description: >-
            Explicit congestion notification, echo.
            1 indicates the peer is ecn capable.
            0 indicates that a packet with ipv4.ecn = 11 in the ip header was 
            received during normal transmission.
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_urg:
          description: >-
            A value of 1 indicates that the urgent pointer field is significant.
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_ack:
          description: >-
            A value of 1 indicates that the ackknowledgment field is significant.
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_psh:
          description: >-
            Asks to push the buffered data to the receiving application. 
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_rst:
          description: >-
            Reset the connection. 
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_syn:
          description: >-
            Synchronize sequenece numbers. 
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ctl_fin:
          description: >-
            Last packet from the sender. 
            Max length is 1 bit.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        window:
          description: >-
            Tcp connection window.
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'

