openapi: 3.1.0

info:
  title: Udp packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Udp:
      description: UDP packet header
      type: object
      properties:
        src_port:
          description: >-
            Udp source port. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        dst_port:
          description: >-
            Tcp destination port. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        length:
          description: >-
            Length in bytes of the udp header and yudp data. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        checksum:
          description: >-
            Checksum field used for error checking of header and data. 
            Max length is 2 bytes.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
 