openapi: 3.1.0

info:
  title: Vlan packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Vlan:
      description: Vlan packet header
      type: object
      properties:
        priority:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        cfi:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        id:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'
        protocol:
          $ref: './patterns.yaml#/components/schemas/Flow.StringPattern'


            
