openapi: 3.1.0

info:
  title: Vlan packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Vlan:
      description: Vlan packet header
      type: object
      required: [type]
      properties:
        priority:
          description: >-
            Vlan priority
          x-fld--offset: 0
          x-fld-t-length: 3
          x-fld-default: 0
          oneOf:
          - type: integer
          - type: string
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        cfi:
          description: >-
            Canonical format indicator
          x-fld-offset: 3
          x-fld-length: 1
          x-fld-default: 0
          oneOf:
          - type: integer
          - type: string
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        id:
          description: >-
            Vlan id
          x-fld-offset: 4
          x-fld-length: 12
          x-fld-default: 0
          oneOf:
          - type: integer
          - type: string
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        protocol:
          description: >-
            Protocol id
          x-fld-offset: 16
          x-fld-length: 16
          x-fld-default: 0800
          oneOf:
          - type: integer
          - type: string
          - $ref: './patterns.yaml#/components/schemas/ValueList'
          - $ref: './patterns.yaml#/components/schemas/Counter'
          - $ref: './patterns.yaml#/components/schemas/Random'
        type:
          description: >-
            Indicates to the server the type of protocol header
          type: string
          enum: [vlan]
          default: vlan


            
