openapi: 3.1.0

info:
  title: Vlan packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Vlan:
      description: VLAN packet header
      type: object
      properties:
        priority:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        cfi:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        id:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'


            
