openapi: 3.1.0

info:
  title: Vlan packet header model
  version: 1.0.0

components:
  schemas:
    Flow.Vlan:
      description: Vlan packet header
      type: object
      properties:
        priority:
          description: >-
            Vlan priority
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        cfi:
          description: >-
            Canonical format indicator
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        id:
          description: >-
            Vlan id
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'
        protocol:
          description: >-
            Protocol id
          type: object
          properties: '../../common/common.yaml#/components/x-inline/Patterns'


            
