openapi: 3.1.0

info:
  title: Emulated bgpv4 protocol model
  version: 1.0.0

components:
  schemas:
    Device.Bgpv4:
      description: >-
        Emulated bgpv4 protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        as_number_2_byte:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        dut_as_number_2_byte:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_number_4_byte:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_number_set_mode:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_type:
          description: >- 
            The type of BGP autonomous system. 
            External BGP (EBGP) is used for BGP links between two or more 
            autonomous systems.
            Internal BGP (IBGP) is used within a single autonomous system.
          type: string
          enum: [IBGP, EBGP]
        hold_time_interval:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        keep_alive_interval:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        graceful_restart:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        authentication:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        ttl:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        dut_ipv4_address:         
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
      
      