openapi: 3.1.0

info:
  title: Emulated bgpv4 protocol model
  version: 1.0.0

components:
  schemas:
    Bgpv4:
      description: >-
        Emulated bgpv4 protocol
      type: object
      required: [name]
      properties:
        name:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        as_number_2_byte:
          type: string
        dut_as_number_2_byte:
          type: string
        as_number_4_byte:
          type: string
        as_number_set_mode:
          type: string
        type:
          description: >- 
            The type of BGP topology. 
            External BGP (EBGP) is used for BGP links between two or more 
            Autonomous Systems.
            Internal BGP (IBGP) is used within a single Autonomous System.
          type: string
          enum: [IBGP, EBGP]
        hold_time_interval:
          type: string
        keep_alive_interval:
          type: string
        graceful_restart:
          type: string
        authentication:
          type: string
        ttl:
          type: string
        dut_ipv4_address:         
          type: string
      
      