openapi: 3.1.0

info:
  title: Emulated protocol device group model
  version: 1.0.0

components:
  schemas:
    DeviceGroup:
      allOf:
      - $ref: '../common.yaml#/components/schemas/UniqueName'
      - type: object
        description: >-
          An abstract container for emulated device containers.
        properties:
          ports: 
            description: >-
              One or more port names that the emulated device containers will share.
            oneOf:
            - type: string
              x-format-ref: '#/components/schemas/Port/name'
            - type: array
              items:
                type: string
                x-format-ref: '#/components/schemas/Port/name'
          devices:
            description: >-
              One or more emulated device containers.
            type: array
            items:
              $ref: './device.yaml#/components/schemas/Device'
                 