openapi: 3.1.0

info:
  title: Emulated protocol device group model
  version: 1.0.1

components:
  schemas:
    Device.DeviceGroup:
      description: >-
        An abstract container for emulated device containers.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        ports: 
          description: >-
            One or more port names that the emulated device containers will share.
          type: array
          items:
            type: string
        devices:
          description: >-
            An unordered list of 0..n emulated device containers.
          type: array
          items:
            $ref: './device.yaml#/components/schemas/Device.Device'
                