openapi: 3.1.0

info:
  title: Emulated protocol device model
  version: 1.0.0

components:
  schemas:
    Device:
      allOf:
      - $ref: '../common.yaml#/components/schemas/UniqueName'
      - type: object
        description: >-
          An abstract container for emulated protocols.
        properties:
          devices_per_port: 
            description: >-
              The number of devices that will be created on each port
            type: integer
            minimum: 1
            maximum: 100000000
          parent: 
            description: >-
              The name of a device container or network container that is 
              the parent of this container. 
              Use this property to establish a hierarchical relationship between 
              containers as a graph. 
            type: string
            x-format-ref: '#/components/schema/Device/name'
          protocols:
            description: >-
              The emulated protocols in this device container
            type: array
            items:
              oneOf:
              - $ref: './ethernet.yaml#/components/schema/Ethernet'
              - $ref: './vlan.yaml#/components/schema/Vlan'
              - $ref: './ipv4.yaml#/components/schema/Ipv4'
              - $ref: './ipv4.yaml#/components/schema/Bgpv4'
