openapi: 3.1.0

info:
  title: Emulated device model
  version: 1.0.0

components:
  schemas:
    Device.Device:
      description: >-
        An abstract container for emulated devices.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        devices_per_port: 
          description: >-
            The number of emulated devices that will be created on each port.
          type: integer
          minimum: 1
          maximum: 100000000
        parent: 
          description: >-
            The name of a device_group, device or network container that is 
            the parent of this container. 
            Use this property to establish a hierarchical relationship between 
             containers.
            An empty or null value indicates the device container is the 
            root of the hierarchy.  
          type: string
        ethernet:
          type: array
          items:
            $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
