openapi: 3.1.0

info:
  title: Emulated device model
  version: 1.0.0

components:
  schemas:
    Device:
      description: >-
        An abstract container for emulated protocols.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        devices_per_port: 
          description: >-
            The number of devices that will be created on each port
          type: integer
          minimum: 1
          maximum: 100000000
        parent: 
          description: >-
            The name of a device container or network container that is 
            the parent of this container. 
            Use this property to establish a hierarchical relationship between 
            device containers. 
          type: string
        protocols:
          description: >-
            The emulated protocols in this device container
          type: array
          items:
            description: Emulated protocol
            type: object
            required: [choice]
            properties:
              choice: 
                type: string
                enum: [ethernet, vlan, ipv4, bgpv4]
              ethernet:
                $ref: './ethernet.yaml#/components/schemas/Ethernet'
              vlan:
                $ref: './vlan.yaml#/components/schemas/Vlan'
              ipv4:
                $ref: './ipv4.yaml#/components/schemas/Ipv4'
              bgpv4:
                $ref: './bgpv4.yaml#/components/schemas/Bgpv4'
