openapi: 3.1.0

info:
  title: Emulated device model
  version: ^0.0.0

components:
  schemas:
    Device.Device:
      description: >-
        An abstract container for emulated devices.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        devices_per_port: 
          description: >-
            The number of emulated devices that will be created on each port.
          type: integer
          default: 1
        ethernets:
          description: >-
            An unordered list of 0..n emulated ethernet protocols.
          type: array
          items:
            $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        devices:
          description: >-
            An unordered list of 0..n emulated device containers.
          type: array
          items:
            $ref: '#/components/schemas/Device.Device'        
        networks:
          description: >-
            An unordered list of 0..n emulated device containers.
          type: array
          items:
            $ref: './network.yaml#/components/schemas/Device.Network'        
