openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: 1.0.0

components:
  schemas:
    Ethernet:
      allOf:
      - $ref: '../common.yaml#/components/schemas/UniqueName'
      - type: object
        properties:
          mac:
            type: string
          mtu:
            type: string
      