openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: 1.0.0

components:
  schemas:
    Ethernet:
      description: >-
        Emulated ethernet protocol
      type: object
      required: [name]
      properties:
        name:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        mac:
          type: string
        mtu:
          type: string
      