openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: 1.0.0

components:
  schemas:
    Device.Ethernet:
      description: >-
        Emulated ethernet protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        mac:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        mtu:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
      