openapi: 3.1.0

info:
  title: Emulated ipv4 protocol model
  version: 1.0.0

components:
  schemas:
    Ipv4:
      description: >-
        Emulated ipv4 protocol
      type: object
      required: [name]
      properties:
        name:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        address:
          type: string
        gateway:
          type: string
        prefix:
          type: string
      