openapi: 3.1.0

info:
  title: Emulated ipv4 protocol model
  version: 1.0.0

components:
  schemas:
    Device.Ipv4:
      description: >-
        Emulated ipv4 protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        address:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        gateway:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
      