openapi: 3.1.0

info:
  title: Emulated ipv4 protocol model
  version: 1.0.0

components:
  schemas:
    Ipv4:
      allOf:
      - $ref: '../common.yaml#/components/schemas/UniqueName'
      - type: object
        properties:
          address:
            type: string
          gateway:
            type: string
          prefix:
            type: string
      