openapi: 3.1.0

info:
  title: Emulated ipv4 protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Ipv4:
      description: >-
        Emulated ipv4 protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        address:
          description: >-
            The ipv4 address.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        gateway:
          description: >-
            The ipv4 address of the gateway.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          description: >-
            The prefix of the ipv4 address.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        bgpv4:
          $ref: './bgpv4.yaml#/components/schemas/Device.Bgpv4'
      