openapi: 3.1.0

info:
  title: Emulated network model
  version: 1.0.0

components:
  schemas:
    Device.Network:
      description: >-
        An abstract container for an emulated network devices.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        network_devices_per_port: 
          description: >-
            The number of emulated network devices that will be created on each port.
          type: integer
        flow-link:
          description: >-
            Identifies which object in another container is the next hop from this container. 
            The name cannot be one of the names in this networks container. 
            An empty value indicates there is no flow link other than the default
            specified by the implementation.
          type:
            string
        choice:
          description: >-
            The type of emulated network devices in the container.
          type: string
          enum: [bgpv4_route_range]       
        bgpv4_route_range:
          $ref: './bgpv4.yaml#/components/schemas/Device.Bgpv4RouteRange'
