openapi: 3.1.0

info:
  title: Emulated device property pattern models
  version: 1.0.0

components:
  schemas:
    Emulated.Pattern:
      description: >-
        A container for emulated device property patterns.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, increment, decrement, random]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        increment:
          $ref: '#/components/schemas/Emulated.Increment'
        decrement:
          $ref: '#/components/schemas/Emulated.Decrement'
        random:
          $ref: '#/components/schemas/Emulated.Random'

    Emulated.Increment:
      description: >-
        An incrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string
    
    Emulated.Decrement:
      description: >-
        A decrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string

    Emulated.Random:
      description: >-
        A repeatable random range pattern.
      type: object
      properties:
        min:
          type: string
        max:
          type: string
        step: 
          type: number
        seed:
          type: string

