openapi: 3.1.0

info:
  title: Emulated protocol model
  version: 1.0.0

components:
  x-inline:
    ParentName: 
      description: >-
        The name of a device/protocol/network container that is 
        the parent of another container. 
        Use this property to establish a parent/child or sibling
        relationship between device containers and protocol containers.
        An empty value indicates the container is the root of the hierarchy.
      type: string
      pattern: ^[\sa-zA-Z0-9-_()><\[\]]+$

  schemas:
    Device.Protocol:
      description: >-
        An abstract container for emulated protocols.
      type: object
      required: [choice]
      properties:
        parent: './protocol.yaml#/components/x-inline/ParentName'
        choice: 
          type: string
          enum: [ethernet, vlan, ipv4, bgpv4]
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        vlan:
          $ref: './vlan.yaml#/components/schemas/Device.Vlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Device.Ipv4'
        bgpv4:
          $ref: './bgpv4.yaml#/components/schemas/Device.Bgpv4'

