openapi: 3.1.0

info:
  title: Emulated vlan protocol model
  version: 1.0.0

components:
  schemas:
    Vlan:
      allOf:
      - $ref: '../common.yaml#/components/schemas/UniqueName'
      - type: object
        properties:
          tpid:
            description: >-
              Vlan tag protocol identifier.
            type: string
          priority:
            description: >-
              Vlan priority.
            type: string
          id:
            description: >-
              Vlan id.
            type: string
      