openapi: 3.1.0

info:
  title: Emulated vlan protocol model
  version: 1.0.0

components:
  schemas:
    Vlan:
      description: >-
        Emulated vlan protocol
      type: object
      required: [name]
      properties:
        name:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        parent:
          $ref: '../common/common.yaml#/components/x-property-fragments/UniqueName'
        tpid:
          description: >-
            Vlan tag protocol identifier.
          type: string
        priority:
          description: >-
            Vlan priority.
          type: string
        id:
          description: >-
            Vlan id.
          type: string
    