openapi: 3.1.0

info:
  title: Emulated vlan protocol model
  version: 1.0.0

components:
  schemas:
    Emulated.Vlan:
      description: >-
        Emulated vlan protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        parent: '../common/common.yaml#/components/x-inline/UniqueName'
        tpid:
          description: >-
            Vlan tag protocol identifier.
          type: string
        priority:
          description: >-
            Vlan priority.
          type: string
        id:
          description: >-
            Vlan id.
          type: string
    