openapi: 3.1.0

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 1.0.0
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers: 
  - url: /

paths: 
  /state:
    description: >-
      State API
    post:
      tags:
        - State
      operationId: setState
      description: >-
        Sets the desired state of the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../state.yaml#/components/schemas/DesiredState'
      responses:
        '204':
          description: No content
    get: 
      tags:
        - State
      operationId: getState
      description: >-
        Gets the current state of the traffic generator
      responses:
        '200':
          description: OK
          content:
            application/json:
            schema:
              $ref: '../control.yaml#/components/schemas/ActualState'

  /ports/results:
    description: >-
      Port results API
    post:
      tags:
        - Results
      operationId: athena.getPortResults
      description: >-
        Get results for ports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ResultInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortResultOutput'
  /flows/results:
    description: >-
      Flow results API
    post:
      tags:
        - Results
      operationId: athena.getFlowResults
      description: >-
        Get results for flows
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ResultInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlowResultOutput'

