openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 1.0.0
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers: 
  - url: /

paths: 
  /state:
    description: >-
      State API
    post:
      tags:
        - State
      operationId: setState
      description: >-
        Sets the desired state of the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../state/state.yaml#/components/schemas/DesiredState'
      responses:
        '204':
          description: No content
    get: 
      tags:
        - State
      operationId: getState
      description: >-
        Gets the current state of the traffic generator
      responses:
        '200':
          description: >-
            The actual state of the traffic generator
          content:
            application/json:
              schema:
                $ref: '../state/state.yaml#/components/schemas/ActualState'



